- rules:
  - ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-generated/quarkus/config/config-to-quarkus.windup.xml-0
    when:
    - dependency:
        artifactID: smallrye-config-source-yaml
        groupID: io.smallrye.config
  - ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-generated/quarkus/config/config-to-quarkus.windup.xml-1
    when:
    - dependency:
        artifactID: smallrye-config-source-yaml
        groupID: io.smallrye.config
