- rules:
  - ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/camel3/camel2/java-multiple-camelcontexts-per-application-not-supported.windup.xml-0
    when:
    - java.referenced:
        location: ANNOTATION
        pattern: org.apache.camel.{class}
  - ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/camel3/camel2/java-multiple-camelcontexts-per-application-not-supported.windup.xml-1
    when:
    - java.referenced:
        location: IMPORT
        pattern: org.apache.camel.cdi.{CdiCamelContextName}
