- rules:
  - ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/technology-usage/configuration-management.windup.xml-0
    tag: []
    when:
    - or:
      - java.dependency:
          name: org.springframework.cloud.spring-cloud-config-client
      - java.dependency:
          name: org.springframework.cloud.spring-cloud-config-client
  - ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/technology-usage/configuration-management.windup.xml-1
    tag: []
    when:
    - file: application{profile}.{extension}
  - ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/technology-usage/configuration-management.windup.xml-2
    tag: []
    when:
    - filecontent:
        filename: application{profile}.{extension}
        pattern: spring.datasource
  - ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/technology-usage/configuration-management.windup.xml-3
    tag: []
    when:
    - filecontent:
        filename: application{profile}.{extension}
        pattern: logging.level.org.springframework
  - ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/technology-usage/configuration-management.windup.xml-4
    tag: []
    when:
    - java.referenced:
        location: ANNOTATION
        pattern: org.springframework.boot.context.properties.ConfigurationProperties
