- - ruleID: ../../windup/windup-rulesets/rules/rules-reviewed/technology-usage/configuration-management.windup.xml-0
    tag: []
    when:
      or:
      - java.dependency:
          lowerbound: 0.0.0
          name: org.springframework.cloud.spring-cloud-config-client
      - java.dependency:
          lowerbound: 0.0.0
          name: org.springframework.cloud.spring-cloud-config-client
  - ruleID: ../../windup/windup-rulesets/rules/rules-reviewed/technology-usage/configuration-management.windup.xml-1
    tag: []
    when:
      builtin.file: application{profile}.{extension}
  - ruleID: ../../windup/windup-rulesets/rules/rules-reviewed/technology-usage/configuration-management.windup.xml-2
    tag: []
    when:
      builtin.filecontent:
        pattern: spring.datasource
  - ruleID: ../../windup/windup-rulesets/rules/rules-reviewed/technology-usage/configuration-management.windup.xml-3
    tag: []
    when:
      builtin.filecontent:
        pattern: logging.level.org.springframework
  - ruleID: ../../windup/windup-rulesets/rules/rules-reviewed/technology-usage/configuration-management.windup.xml-4
    tag: []
    when:
      java.referenced:
        location: ANNOTATION
        pattern: org.springframework.boot.context.properties.ConfigurationProperties
