- rules:
  - message: This is a JDBC URL, which describes the basic information about. where
      and how to connect to the database.. This particular URL points to a PostgreSQL
      database.. In EAP 6, the databases are configured in these steps:. 1. Add the
      JDBC driver as an EAP 6 module. Download it [here](https://jdbc.postgresql.org/download.html)..
      2. Create a datasource (actual values need to be changed):. ```. $ EAP_HOME/bin/jboss-cli
      --connect. [standalone@localhost:9999 /] data-source add --name=ExampleDS --jndi-name=java:/ExampleDS
      \\. --connection-url=... --driver-name=postgresql \\. --user-name=... --password=....
      ```. 3. Use the datasource according to JPA 2.0 standards.
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-0
    when:
    - xml:
        XPath: /datasources/local-tx-datasource/connection-url[contains(text(),'jdbc:postgres')]
        filepaths:
        - '{*}-ds.xml'
  - message: This is a JDBC URL, which describes the basic information about. where
      and how to connect to the database.. This particular URL points to an Oracle
      Database.. In EAP 6, the databases are configured in these steps:. 1. Add the
      JDBC driver as an EAP 6 module. Download it [here](http://www.oracle.com/technetwork/database/features/jdbc/index-091264.html)..
      2. Create a datasource (actual values need to be changed):. ```. $ EAP_HOME/bin/jboss-cli
      --connect. [standalone@localhost:9999 /] data-source add --name=ExampleDS --jndi-name=java:/ExampleDS
      \\. --connection-url=... --driver-name=oracle \\. --user-name=... --password=....
      ```. 3. Use the datasource according to JPA 2.0 standards.. ```. @PersistenceContext
      EntityManager em;. ```
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-1
    when:
    - xml:
        XPath: /datasources/local-tx-datasource/connection-url[contains(text(),'jdbc:oracle')]
        filepaths:
        - '{*}-ds.xml'
  - message: This is a JDBC URL, which describes the basic information about. where
      and how to connect to the database.. This particular URL points to an Microsoft
      SQL Server.. In EAP 6, the databases are configured in these steps:. 1. Add
      the JDBC driver as an EAP 6 module. Download it [here](https://msdn.microsoft.com/en-us/sqlserver/aa937724.aspx)..
      2. Create a datasource (actual values need to be changed):. ```. $ EAP_HOME/bin/jboss-cli
      --connect. [standalone@localhost:9999 /] data-source add --name=ExampleDS --jndi-name=java:/ExampleDS
      \\. --connection-url=... --driver-name=mssql \\. --user-name=... --password=....
      ```. 3. Use the datasource according to JPA 2.0 standards.. ```. @PersistenceContext
      EntityManager em;. ```
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-2
    when:
    - xml:
        XPath: /datasources/local-tx-datasource/connection-url[contains(text(),'jdbc:sqlserver')]
        filepaths:
        - '{*}-ds.xml'
  - message: 'The `<Connector port="..."/>` attribute specifies the port. on which
      JBoss Web listens for requests.. In JBoss EAP 6, set the port number using JBoss
      CLI or a web console:. ```. :read-children-names(child-type=interface). /subsystem=web/connector=http/:read-resource.
      ## Notice the "socket-binding" => "http". /socket-binding-group=standard-sockets/socket-binding=http/:read-resource.
      ## Now set the HTTP port to what you need.. /socket-binding-group=standard-sockets/socket-binding=http/:write-attribute(name=port,
      value=80). ```'
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-3
    when:
    - xml:
        XPath: /Server/Service/Connector/@port
        filepaths:
        - server.xml
  - message: 'The `<Connector protocol="..."/>` attribute specifies the protocol.
      of the particular JBoss Web connector.. In JBoss EAP 6, set the protocol using
      JBoss CLI or a web console:. ```. :read-children-names(child-type=interface).
      /subsystem=web/connector=http/:read-resource. /subsystem=web/connector=http/:write-attribute(name=protocol,
      value=HTTP/1.1). ##  To enable NIO protocol:. /subsystem=web/connector=http/:write-attribute(name=protocol,
      value=org.apache.coyote.http11.Http11NioProtocol). ```'
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-4
    when:
    - xml:
        XPath: /Server/Service/Connector/@protocol
        filepaths:
        - server.xml
  - message: 'The `<Connector maxThreads="..."/>` attribute specifies the. maximum
      number of JBoss Web Connector threads.. In JBoss EAP 6, the. [connections do
      not map 1:1 to threads](https://access.redhat.com/solutions/389513),. thanks
      to use of `javax.nio`. There can be more connection. served by less threads..
      You can set the maximum number of connections using JBoss CLI or a web console:.
      ```. /subsystem=web/connector=http/:write-attribute(name=max-connections, value=200).
      ```. The default is 512 per CPU core.. You can limit the number of threads using
      JBoss CLI or a web console:. ```. /subsystem=web/connector=http/:read-resource.
      ##  Define a thread factory. /subsystem=threads/thread-factory=http-connector-factory:add(thread-name-pattern="HTTP-%t",
      priority="9", group-name="uq-thread-pool"). ##  Create an executor. /subsystem=threads/unbounded-queue-thread-pool=uq-thread-pool:add(thread-factory="http-connector-factory",
      keepalive-time=\{time=30, unit="seconds"}, max-threads=30). ##  Make the HTTP
      web connector use this thread pool. /subsystem=web/connector=http:write-attribute(name=executor,
      value="uq-thread-pool"). ```'
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-5
    when:
    - xml:
        XPath: /Server/Service/Connector/@maxThreads
        filepaths:
        - server.xml
  - message: The `<Connector connectionTimeout="..."/>` attribute specifies the connection
      timeout. of the particular JBoss Web connector.. In JBoss EAP 6, set the connection
      timeout using a system property:. ```. /system-property=org.apache.coyote.ajp.DEFAULT_CONNECTION_TIMEOUT/:add(value=600000).
      /system-property=org.apache.coyote.http11.DEFAULT_CONNECTION_TIMEOUT/:add(value=120000).
      ```
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-6
    when:
    - xml:
        XPath: /Server/Service/Connector/@connectionTimeout
        filepaths:
        - server.xml
  - message: JBoss Web's `emptySessionPath` option sets the path of a session cookie
      to '/'.. In JBoss EAP 6, the path is set in a web framework, or in `web.xml`:.
      ```xml. <session-config>. <cookie-config>. <path>/</path>. <http-only>true</http-only>.
      <secure/>. </cookie-config>. <tracking-mode>COOKIE</tracking-mode>. </session-config>.
      ```. Not to be confused with Undertow's `path` which sets the session files
      storage path.
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-7
    when:
    - xml:
        XPath: /Server/Service/Connector/@emptySessionPath
        filepaths:
        - server.xml
  - message: The `<Connector enableLookups="..."/>` attribute. enables DNS lookup
      through `request.getRemoteHost()`.. Define this setting using JBoss CLI or the
      web console.. ```. /subsystem=web/connector=http:write-attribute(name=enable-lookups,
      value=true). ```
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-8
    when:
    - xml:
        XPath: /Server/Service/Connector/@enableLookups
        filepaths:
        - server.xml
  - message: The `<Connector redirectPort="..."/>` attribute. specifies  a port number
      to be used in cases of redirection; the common ones being redirection to secure
      (HTTPS) or AJP connector.. Define this setting using JBoss CLI or the web console..
      ```. /subsystem=web/connector=http:write-attribute(name=redirect-port, value=8433).
      ```
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-9
    when:
    - xml:
        XPath: /Server/Service/Connector/@redirectPort
        filepaths:
        - server.xml
  - message: The `<Connector scheme="..."/>` attribute. specifies the web connector
      scheme, such as HTTP or HTTPS.. Define this setting using JBoss CLI or the web
      console.. ```. /subsystem=web/connector=http:write-attribute(name=scheme, value=http).
      ```
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-10
    when:
    - xml:
        XPath: /Server/Service/Connector/@scheme
        filepaths:
        - server.xml
  - message: The `secure` option tells the browser (or other HTTP clients) to only
      send the cookie over SSL connections.. This means the cookie will not be available
      to any part of the site that is not secure.. If you serve both protocols, the
      non-secure http connection will then use URL re-writing with the long ";jsessionid=XXXXXXX"
      appended to every URL.. You should set this to true ONLY if you are only serving
      https content, for mixed content this setting in NOT recomended.. Define this
      setting using JBoss CLI or the web console.. ```. /subsystem=web/connector=http:write-attribute(name=secure,
      value=true). ```
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-11
    when:
    - xml:
        XPath: /Server/Service/Connector[@secure='true']
        filepaths:
        - server.xml
  - message: In JBoss Web, the `jvmRoute` attribute of the Engine element allows the
      load balancer to match requests. to the JVM currently responsible for updating
      the relevant session.. It does this by appending the name of the JVM to the
      `JSESSIONID` of the request,. and matching this against the worker name provided
      in `workers.properites`.. In JBoss EAP 6,. the `jvmRoute` is set to the same
      value as the server name.. If you need to customize it, you can use a command
      like the following.. Replace or remove the `/profile=ha portion` of the command,
      depending on which profile you use or. whether you use a standalone server..
      Replace the string `CUSTOM_ROUTE_NAME` with your custom jvmRoute name.. ```.
      /profile=ha/subsystem=web:write-attribute(name="instance-id", value="CUSTOM_ROUTE_NAME").
      ```. The default can be overriden by setting the `jvmRoute` system property.
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-12
    when:
    - xml:
        XPath: /Server/Service/Engine/@jvmRoute
        filepaths:
        - server.xml
  - message: JBoss EAP 4 and 5 allow overriding the container settings in `jboss.xml`
      files.. Extending `"Standard Stateless SessionBean"` allows configuring the
      instance pool.. Bean-specific instance pool can be set with one line in JBoss
      EAP 6 management CLI.
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-13
    when:
    - xml:
        XPath: /jboss/container-configurations/container-configuration[@extends='Standard
          Stateless SessionBean']
        filepaths:
        - jboss.xml
  - message: JBoss EAP 4 allows overriding the container settings in `jboss.xml` files..
      Extending `"Clustered Stateless SessionBean"` allows configuring the instance
      pool.. Bean-specific instance pool can be set with one line in JBoss EAP 6 management
      CLI.
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-14
    when:
    - xml:
        XPath: /jboss/container-configurations/container-configuration[@extends='Clustered
          Stateless SessionBean']
        filepaths:
        - jboss.xml
  - message: JBoss EAP 4 and 5 allow overriding the container settings in `jboss.xml`
      files.. Extending `"Standard Message Driven Bean"` allows configuring the instance
      pool.. MDB's bean-specific instance pool can be set with one line in JBoss EAP
      6 management CLI.. Use the `bean-instance-pool-ref` CLI node of the respective
      configuration part.
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-15
    when:
    - xml:
        XPath: /jboss/container-configurations/container-configuration[@extends='Standard
          Message Driven Bean']
        filepaths:
        - jboss.xml
  - message: JBoss EAP 4 and 5 allow overriding the container settings in `jboss.xml`
      files.. Extending `"Singleton Message Driven Bean"` allows configuring the instance
      pool.. Singleton Message Driven Bean's bean-specific bean-specific instance
      pool can be set with one line in JBoss EAP 6 management CLI.. Use the `bean-instance-pool-ref`
      CLI node of the respective configuration part.
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-16
    when:
    - xml:
        XPath: /jboss/container-configurations/container-configuration[@extends='Singleton
          Message Driven Bean']
        filepaths:
        - jboss.xml
  - message: JBoss EAP 4 and 5 allow overriding the container settings in `jboss.xml`
      files.. Extending `"Standard Message Inflow Driven Bean"` allows configuring
      the instance pool.. Standard Message Inflow Driven Bean's bean-specific bean-specific
      instance pool can be set with one line in JBoss EAP 6 management CLI.. Use the
      `bean-instance-pool-ref` CLI node of the respective configuration part.
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml-17
    when:
    - xml:
        XPath: /jboss/container-configurations/container-configuration[@extends='Standard
          Message Inflow Driven Bean']
        filepaths:
        - jboss.xml
