- - message: Replace the `io.fabric8:kubernetes-client` dependency with the Quarkus
      dependency `io.quarkus:quarkus-kubernetes-client`. Further information in the
      link below.
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-generated/quarkus/kubernetes/kubernetes-to-quarkus.windup.xml-0
    when:
      java.dependency:
        name: io.fabric8.kubernetes-client
  - message: Replace the `io.fabric8:kubernetes-client` dependency with the Quarkus
      dependency `io.quarkus:quarkus-kubernetes-client`. Further information in the
      link below.
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-generated/quarkus/kubernetes/kubernetes-to-quarkus.windup.xml-1
    when:
      java.dependency:
        name: io.fabric8.kubernetes-client
