- rules:
  - message: If you migrate your application to JBoss EAP XP 3.0 (or later), and want
      to ensure its Maven building, running or testing works as expected, rename the
      configuration element `extraServerContent` to `extraServerContentDirs`.
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eapxp/eapxp2/eapxp_bootable_jar_maven_plugin_configuration_changes.mta.xml-0
    when:
    - xmlfile: null
