- rules:
  - ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/azure/eap/eap-to-azure-appservice-environment-variables.windup.xml-0
    when:
    - or:
      - java.referenced:
          location: METHOD_CALL
          pattern: java.lang.System.getenv({*})
      - java.referenced:
          location: METHOD_CALL
          pattern: java.lang.System.getProperty({*})
