- - message: App Service - The application reads environment variables.. Any environment
      variables used in the code will need to be defined as App Settings, which are
      exposed. as environment variables in App Service.. Any System properties that
      the code depends on will need to be provided either in a custom Startup Script.
      or by defining an App Setting with the name JAVA_OPTS and include any system
      properties in it.
    ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/azure/eap/eap-to-azure-appservice-environment-variables.windup.xml-0
    when:
      or:
      - java.referenced:
          location: METHOD_CALL
          pattern: java.lang.System.getenv(*)
      - java.referenced:
          location: METHOD_CALL
          pattern: java.lang.System.getProperty(*)
