- rules:
  - ruleID: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/quarkus/springboot/springboot-cloud-config-client-to-quarkus.windup.xml-0
    when:
    - or:
      - dependency:
          artifactID: spring-cloud-config-client
          groupID: org.springframework.cloud
      - dependency:
          artifactID: spring-cloud-config-client
          groupID: org.springframework.cloud
