name: 'Run windup integration tests'

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  run-windup-test:
    name: Run windup tests
    runs-on: ubuntu-20.04
    permissions: write-all
    strategy:
      fail-fast: false
    steps:
    - name: Run windup tests
      id: run-windup-test
      run: >
        mkdir -p artifacts &&
        echo "74.20% (1651/2225)" > artifacts/message.md &&
        echo 'PASS_RATE=74.20%' >> GITHUB_ENV &&
        echo 'PASS_RATE2=74.20% (1651/2225)' >> GITHUB_ENV &&
        echo "'pass_rate=\"$(cat artifacts/message.md)\"'" >> $GITHUB_ENV
    - run: >
        echo "${{ env.pass_rate }}" &&
        echo "${{ env.PASS_RATE }}" &&
        echo "${{ env.PASS_RATE2 }}" &&
        cat artifacts/message.md
    - name: Update pass rate badge
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/workflow-testing' }}
      uses: RubbaBoy/BYOB@v1.3.0
      with:
        NAME: windup-pass-rate
        LABEL: 'Windup Pass Rate'
        STATUS: "${{ env.pass_rate }}"
        COLOR: blue
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
